spring:
  datasource:
  #
  url: jdbc:h2:./datajpa
  username: sa
  password: datajpa
  driver-class-name: org.h2.Driver
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      # show_sql: true # JPA? ???? ??? ??? ?? ??
      format_sql: true
logging.level:
  org.hibernate.SQL: debug # JPA? ???? ??? ??? ??? ??
#  org.hibernate.type: trace # ???? ?????? ? ? ?? ??