spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl3
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true # JPQL 볼 수 있음
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
